FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["LeoECS\\src\\EcsSystem.bf", "LeoECS\\src\\EcsHelpers.bf", "LeoECS\\src\\EcsFilter.bf", "LeoECS\\src\\EcsWorld.bf"]

[MainWindow]
X = 89
Y = 56
Width = 2147
Height = 1233
ShowKind = "Normal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 370.0
RequestedHeight = 220.0
SizePriority = 220.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 395.0
RequestedHeight = 220.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 110.8333
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "EcsSystem.bf"
TabWidth = 100.8333
Type = "SourceViewPanel"
FilePath = "LeoECS\\src\\EcsSystem.bf"
CursorPos = 15347
VertPos = 8952.0
ProjectName = "LeoECS"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EcsHelpers.bf"
TabWidth = 104.1667
Type = "SourceViewPanel"
FilePath = "LeoECS\\src\\EcsHelpers.bf"
CursorPos = 1794
ProjectName = "LeoECS"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EcsWorld.bf"
TabWidth = 95.83333
Type = "SourceViewPanel"
FilePath = "LeoECS\\src\\EcsWorld.bf"
CursorPos = 1185
ProjectName = "LeoECS"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EcsFilter.bf"
TabWidth = 88.33333
Type = "SourceViewPanel"
FilePath = "LeoECS\\src\\EcsFilter.bf"
CursorPos = 58152
ProjectName = "LeoECS"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 275.0
RequestedHeight = 327.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 275.0
RequestedHeight = 275.0
SizePriority = 0.4631057
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 81.66666
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 95.83333
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.0
Type = "WatchPanel"
Columns = [{Width = 220.0}, {Width = 220.0}, {Width = 220.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 76.66666
Type = "AutoWatchPanel"
Columns = [{Width = 220.0}, {Width = 220.0}, {Width = 220.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 275.0
RequestedHeight = 275.0
SizePriority = 0.5368943
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 115.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 93.33333
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 103.3333
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 110.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 88.33333
Type = "OutputPanel"
